connection:
  socket: {host: 10.42.0.180, port: 9000}
  serial: {port: /dev/ttyTHS1, baudrate: 1000000}
defaults: {speed: 100, press_duration: 1.0, lift_duration: 0.1, count: 1}
buttons:
  bluetooth:
    name: Bluetooth 按鈕
    description: 藍牙控制按鈕
    down_angles: [16.5, -51, -130, 73.7, 0, 0]
    up_angles: [16.5, -13, -130, 73.7, 0, 0]
    speed: 100
    count: 2
    lift_duration: 0.1
    press_duration: 1.0
    vision:
      observe_angles: [1.75, 9.93, -134.73, 34.45, 2.19, -45.08]
      roi: {x: 402, y: 335, width: 68, height: 65}
  aux2:
    name: AUX2 按鈕
    description: 輔助控制按鈕 2
    down_angles: [14, -58, -92, 23.9, 0, 0]
    up_angles: [14, -15, -92, 23.9, 0, 0]
    speed: 100
    count: 2
    lift_duration: 0.5
    press_duration: 1.0
    vision:
      observe_angles: [1.75, 9.93, -134.73, 34.45, 2.19, -45.08]
      roi: {x: 339, y: 336, width: 65, height: 65}
  light3:
    name: Light3 按鈕
    description: 燈光控制 3
    down_angles: [13, -58, -85, 23.8, 0, 0]
    up_angles: [13, -35, -85, 23.8, 0, 0]
    speed: 100
    count: 2
    lift_duration: 0.5
    press_duration: 1.0
    vision:
      observe_angles: [2.02, 6.76, -135.26, 32.78, 3.07, -44.2]
      roi: {x: 202, y: 346, width: 75, height: 69}
  light8:
    name: Light8 按鈕
    description: 燈光控制 8
    down_angles: [11.9, -62, -77.4, 23.8, 0, 0]
    up_angles: [11.9, -35, -77.4, 23.8, 0, 0]
    speed: 100
    count: 1
    lift_duration: 0.1
    press_duration: 1.0
    vision:
      observe_angles: [1.75, 9.93, -134.73, 34.45, 2.19, -45.08]
      roi: {x: 207, y: 340, width: 70, height: 66}
  select:
    name: Select 按鈕
    description: 選擇按鈕
    down_angles: [11.6, -63.8, -69, 22.5, 0, 0]
    up_angles: [11.6, -35, -69, 22.5, 0, 0]
    speed: 100
    count: 1
    lift_duration: 0.1
    press_duration: 1.0
    vision:
      observe_angles: [1.75, 9.93, -134.73, 34.45, 2.19, -45.08]
      roi: {x: 128, y: 341, width: 77, height: 69}
  aux1:
    name: AUX1 按鈕
    description: 輔助控制按鈕 1
    down_angles: [8, -59, -92, 25, 0, 0]
    up_angles: [8, -35, -92, 25, 0, 0]
    speed: 100
    count: 1
    lift_duration: 0.1
    press_duration: 1.0
    vision:
      observe_angles: [1.75, 9.93, -134.73, 34.45, 2.19, -45.08]
      roi: {x: 339, y: 273, width: 67, height: 63}
  light2:
    name: Light2 按鈕
    description: 燈光控制 2
    down_angles: [6.8, -59.5, -85, 25, 0, 0]
    up_angles: [6.8, -35, -85, 25, 0, 0]
    speed: 100
    count: 1
    lift_duration: 0.1
    press_duration: 1.0
    vision:
      observe_angles: [1.49, 9.22, -135.0, 33.57, 2.63, -44.82]
      roi: {x: 248, y: 280, width: 67, height: 62}
    aruco_reference:
      angles: [1.49, 9.22, -135.0, 33.57, 2.63, -44.82]
      markers:
      - center: [527, 53.25]
        center_x: 527
        center_y: 53.25
        corners:
        - [554, 25]
        - [553, 83]
        - [500, 82]
        - [501, 23]
        id: 2
      - center: [524, 422.25]
        center_x: 524
        center_y: 422.25
        corners:
        - [499, 451]
        - [498, 397]
        - [549, 394]
        - [550, 447]
        id: 1
      - center: [42.5, 60.25]
        center_x: 42.5
        center_y: 60.25
        corners:
        - [75, 29]
        - [76, 92]
        - [10, 92]
        - [9, 28]
        id: 3
      - center: [55, 435]
        center_x: 55
        center_y: 435
        corners:
        - [85, 404]
        - [88, 463]
        - [26, 466]
        - [21, 407]
        id: 4
      timestamp: 1763110704.7123375
  light7:
    name: Light7 按鈕
    description: 燈光控制 7
    down_angles: [6.8, -59.5, -79, 25, 0, 0]
    up_angles: [6.8, -35, -79, 25, 0, 0]
    speed: 100
    count: 1
    lift_duration: 0.1
    press_duration: 1.0
    vision:
      observe_angles: [1.75, 9.93, -134.73, 34.45, 2.19, -45.08]
      roi: {x: 205, y: 276, width: 72, height: 66}
  door_lock:
    name: Door Lock 按鈕
    description: 門鎖控制
    down_angles: [3.5, -58, -90, 25, 0, 0]
    up_angles: [3.5, -35, -90, 25, 0, 0]
    speed: 100
    count: 1
    lift_duration: 0.1
    press_duration: 1.0
    vision:
      observe_angles: [1.75, 9.93, -134.73, 34.45, 2.19, -45.08]
      roi: {x: 338, y: 210, width: 68, height: 65}
  light1:
    name: Light1 按鈕
    description: 燈光控制 1
    down_angles: [3.5, -60, -82, 25, 0, 0]
    up_angles: [3.5, -35, -82, 25, 0, 0]
    speed: 100
    count: 1
    lift_duration: 0.1
    press_duration: 0.5
    vision:
      observe_angles: [1.93, 8.34, -135.0, 33.57, 2.63, -44.56]
      roi: {x: 197, y: 205, width: 71, height: 67}
    aruco_reference:
      angles: [1.93, 8.34, -135.0, 33.57, 2.63, -44.56]
      markers:
      - center: [527, 53.25]
        center_x: 527
        center_y: 53.25
        corners:
        - [554, 25]
        - [553, 83]
        - [500, 82]
        - [501, 23]
        id: 2
      - center: [524, 422.25]
        center_x: 524
        center_y: 422.25
        corners:
        - [499, 451]
        - [498, 397]
        - [549, 394]
        - [550, 447]
        id: 1
      - center: [42.5, 60.25]
        center_x: 42.5
        center_y: 60.25
        corners:
        - [75, 29]
        - [76, 92]
        - [10, 92]
        - [9, 28]
        id: 3
      - center: [55, 435]
        center_x: 55
        center_y: 435
        corners:
        - [85, 404]
        - [88, 463]
        - [26, 466]
        - [21, 407]
        id: 4
      timestamp: 1763110704.7123375
  light6:
    name: Light6 按鈕
    description: 燈光控制 6
    down_angles: [3.3, -59, -77, 25, 0, 0]
    up_angles: [3.3, -35, -77, 25, 0, 0]
    speed: 100
    count: 1
    lift_duration: 0.1
    press_duration: 1.0
    vision:
      observe_angles: [1.75, 9.93, -134.73, 34.45, 2.19, -45.08]
      roi: {x: 202, y: 211, width: 74, height: 66}
  retract:
    name: Retract 按鈕
    description: 縮回控制
    down_angles: [3.1, -68, -67, 22, 0, 0]
    up_angles: [3.1, -35, -67, 22, 0, 0]
    speed: 100
    count: 1
    lift_duration: 0.1
    press_duration: 7.0
    vision:
      observe_angles: [1.75, 9.93, -134.73, 34.45, 2.19, -45.08]
      roi: {x: 107, y: 212, width: 96, height: 65}
  tanker_heater:
    name: Tanker Heater 按鈕
    description: 水箱加熱器
    down_angles: [-3, -58, -83, 20, 0, 0]
    up_angles: [-3, -25, -83, 20, 0, 0]
    speed: 100
    count: 4
    lift_duration: 0.1
    press_duration: 1.0
    vision:
      observe_angles: [1.75, 9.93, -134.73, 34.45, 2.19, -45.08]
      roi: {x: 339, y: 147, width: 65, height: 65}
  gas:
    name: Gas 按鈕
    description: 瓦斯控制
    down_angles: [-2.7, -60, -75.5, 17, 0, 0]
    up_angles: [-2.7, -30, -75.5, 17, 0, 0]
    speed: 100
    count: 4
    lift_duration: 0.1
    press_duration: 1.0
    vision:
      observe_angles: [1.75, 9.93, -134.73, 34.45, 2.19, -45.08]
      roi: {x: 273, y: 147, width: 66, height: 64}
  light5:
    name: Light5 按鈕
    description: 燈光控制 5
    down_angles: [-1.7, -66, -70, 20, 0, 0]
    up_angles: [-1.7, -35, -70, 20, 0, 0]
    speed: 100
    count: 1
    lift_duration: 0.1
    press_duration: 1.0
    vision:
      observe_angles: [1.75, 9.93, -134.73, 34.45, 2.19, -45.08]
      roi: {x: 205, y: 148, width: 68, height: 62}
  extend:
    name: Extend 按鈕
    description: 伸展控制
    down_angles: [-1.7, -69, -62, 19, 0, 0]
    up_angles: [-1.8, -30, -61, 20, 0, 0]
    speed: 100
    count: 1
    lift_duration: 0.1
    press_duration: 7.0
    vision:
      observe_angles: [1.75, 9.93, -134.73, 34.45, 2.19, -45.08]
      roi: {x: 103, y: 145, width: 100, height: 66}
  water_pump:
    name: Water Pump 按鈕
    description: 水泵控制
    down_angles: [-8.5, -58, -80, 20, 0, 0]
    up_angles: [-8.5, -25, -80, 20, 0, 0]
    speed: 100
    count: 4
    lift_duration: 0.1
    press_duration: 1.0
    vision:
      observe_angles: [1.75, 9.93, -134.73, 34.45, 2.19, -45.08]
      roi: {x: 338, y: 85, width: 65, height: 61}
  water_heater:
    name: Water Heater 按鈕
    description: 熱水器控制
    down_angles: [-8.2, -62, -72.2, 20, 0, 0]
    up_angles: [-8.2, -25, -72.2, 20, 0, 0]
    speed: 100
    count: 4
    lift_duration: 0.1
    press_duration: 1.0
    vision:
      observe_angles: [1.75, 9.93, -134.73, 34.45, 2.19, -45.08]
      roi: {x: 272, y: 79, width: 66, height: 67}
  light4:
    name: Light4 按鈕
    description: 燈光控制 4
    down_angles: [-7.9, -64.2, -65, 20, 0, 0]
    up_angles: [-7.9, -25, -65, 20, 0, 0]
    speed: 100
    count: 2
    lift_duration: 0.1
    press_duration: 1.0
    vision:
      observe_angles: [1.75, 9.93, -134.73, 34.45, 2.19, -45.08]
      roi: {x: 203, y: 76, width: 71, height: 69}
  hvac:
    name: HVAC 按鈕
    description: 空調控制
    down_angles: [-7.1, -68.8, -61.6, 23.9, 0, 0]
    up_angles: [-6.8, -52.5, -61.3, 23.3, 0, 0]
    speed: 100
    count: 1
    lift_duration: 0.1
    press_duration: 1.0
    vision:
      observe_angles: [1.75, 9.93, -134.73, 34.45, 2.19, -45.08]
      roi: {x: 125, y: 74, width: 74, height: 71}
  camera_observe:
    name: 相機觀測點
    description: 相機觀測位置
    down_angles: [1, 11, -134, 35, 1, -45]
    up_angles: [1, 11, -134, 35, 1, -45]
    speed: 50
    count: 1
    lift_duration: 0.1
    press_duration: 0.0
  fridge_observe:
    name: 冰箱 按鈕
    description: 冰箱控制
    down_angles: [1, 11, -134, 35, 1, -45]
    up_angles: [1, 11, -134, 35, 1, -45]
    speed: 50
    count: 1
    lift_duration: 0.1
    press_duration: 0.0
    vision:
      observe_angles: [1.75, 9.93, -134.73, 34.45, 2.19, -45.08]
      roi: {x: 402, y: 82, width: 68, height: 67}
  mic_observe:
    name: 相機觀測點
    description: 相機觀測位置
    down_angles: [1, 11, -134, 35, 1, -45]
    up_angles: [1, 11, -134, 35, 1, -45]
    speed: 50
    count: 1
    lift_duration: 0.1
    press_duration: 0.0
    vision:
      observe_angles: [1.75, 9.93, -134.73, 34.45, 2.19, -45.08]
      roi: {x: 497, y: 157, width: 27, height: 67}
  wifi_observe:
    name: 相機觀測點
    description: 相機觀測位置
    down_angles: [1, 11, -134, 35, 1, -45]
    up_angles: [1, 11, -134, 35, 1, -45]
    speed: 50
    count: 1
    lift_duration: 0.1
    press_duration: 0.0
    vision:
      observe_angles: [1.75, 9.93, -134.73, 34.45, 2.19, -45.08]
      roi: {x: 497, y: 262, width: 33, height: 69}
  awning1_observe:
    name: 相機觀測點
    description: 相機觀測位置
    down_angles: [1, 11, -134, 35, 1, -45]
    up_angles: [1, 11, -134, 35, 1, -45]
    speed: 50
    count: 1
    lift_duration: 0.1
    press_duration: 0.0
    vision:
      observe_angles: [1.75, 9.93, -134.73, 34.45, 2.19, -45.08]
      roi: {x: 181, y: 285, width: 21, height: 48}
  awning2_observe:
    name: 相機觀測點
    description: 相機觀測位置
    down_angles: [1, 11, -134, 35, 1, -45]
    up_angles: [1, 11, -134, 35, 1, -45]
    speed: 50
    count: 1
    lift_duration: 0.1
    press_duration: 0.0
    vision:
      observe_angles: [1.75, 9.93, -134.73, 34.45, 2.19, -45.08]
      roi: {x: 163, y: 284, width: 20, height: 49}
  slide1_observe:
    name: 相機觀測點
    description: 相機觀測位置
    down_angles: [1, 11, -134, 35, 1, -45]
    up_angles: [1, 11, -134, 35, 1, -45]
    speed: 50
    count: 1
    lift_duration: 0.1
    press_duration: 0.0
    vision:
      observe_angles: [1.75, 9.93, -134.73, 34.45, 2.19, -45.08]
      roi: {x: 147, y: 287, width: 18, height: 45}
  slide2_observe:
    name: 相機觀測點
    description: 相機觀測位置
    down_angles: [1, 11, -134, 35, 1, -45]
    up_angles: [1, 11, -134, 35, 1, -45]
    speed: 50
    count: 1
    lift_duration: 0.1
    press_duration: 0.0
    vision:
      observe_angles: [1.75, 9.93, -134.73, 34.45, 2.19, -45.08]
      roi: {x: 129, y: 286, width: 18, height: 48}
  slide3_observe:
    name: 相機觀測點
    description: 相機觀測位置
    down_angles: [1, 11, -134, 35, 1, -45]
    up_angles: [1, 11, -134, 35, 1, -45]
    speed: 50
    count: 1
    lift_duration: 0.1
    press_duration: 0.0
    vision:
      observe_angles: [1.75, 9.93, -134.73, 34.45, 2.19, -45.08]
      roi: {x: 110, y: 287, width: 19, height: 44}
  slide4_observe:
    name: 相機觀測點
    description: 相機觀測位置
    down_angles: [1, 11, -134, 35, 1, -45]
    up_angles: [1, 11, -134, 35, 1, -45]
    speed: 50
    count: 1
    lift_duration: 0.1
    press_duration: 0.0
    vision:
      observe_angles: [1.75, 9.93, -134.73, 34.45, 2.19, -45.08]
      roi: {x: 91, y: 287, width: 21, height: 48}
  slide5_observe:
    name: 相機觀測點
    description: 相機觀測位置
    down_angles: [1, 11, -134, 35, 1, -45]
    up_angles: [1, 11, -134, 35, 1, -45]
    speed: 50
    count: 1
    lift_duration: 0.1
    press_duration: 0.0
    vision:
      observe_angles: [1.75, 9.93, -134.73, 34.45, 2.19, -45.08]
      roi: {x: 72, y: 287, width: 20, height: 47}
  lockout_observe:
    name: 相機觀測點
    description: 相機觀測位置
    down_angles: [1, 11, -134, 35, 1, -45]
    up_angles: [1, 11, -134, 35, 1, -45]
    speed: 50
    count: 1
    lift_duration: 0.1
    press_duration: 0.0
    vision:
      observe_angles: [1.75, 9.93, -134.73, 34.45, 2.19, -45.08]
      roi: {x: 50, y: 284, width: 23, height: 55}
